name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip ninja-build gperf
        pip3 install west

    - name: Configure Zephyr environment
      run: |
        west init -l path/to/west.yml
        west update
        west zephyr-export
        pip3 install -r zephyr/scripts/requirements.txt

    - name: Clean build directory
      run: |
        rm -rf build

    - name: Build firmware
      run: |
        west build -p -b nice_nano_v2 -d build -- -DSHIELD="lily58_left nice_view_adapter nice_view"

    - name: Show build logs
      run: |
        cat build/zephyr/.config
        cat build/CMakeFiles/CMakeError.log || true
