name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python and Install Dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install west
        pip install -r zephyr/scripts/requirements.txt

    - name: Initialize and Update West Workspace
      run: |
        source venv/bin/activate
        if [ ! -d ".west" ]; then
          west init -l config/west.yml
        fi
        west update

    - name: Install Zephyr SDK
      run: |
        wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.3/zephyr-sdk-0.16.3-linux-x86_64-setup.run
        chmod +x zephyr-sdk-0.16.3-linux-x86_64-setup.run
        ./zephyr-sdk-0.16.3-linux-x86_64-setup.run -- -d $HOME/zephyr-sdk
        echo "export ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
        echo "export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

    - name: Build Firmware
      run: |
        source venv/bin/activate
        west build -b nice_nano_v2 -d build/ -s zmk/app --pristine -- -DSHIELD=lily58_left