name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install west

  build:
    needs: pre-build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install west

    - name: Install west
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install west

    - name: Initialize west workspace
      run: |
        source venv/bin/activate
        if [ ! -d ".west" ]; then
          west init -l config/west.yml
        fi
        west update

    - name: Export Zephyr environment
      run: |
        source venv/bin/activate
        pip install west
        west zephyr-export

    - name: Install Zephyr dependencies
      run: |
        source venv/bin/activate
        pip install -r zephyr/scripts/requirements.txt

    - name: Configure Zephyr SDK
      run: |
        echo "export ZEPHYR_TOOLCHAIN_VARIANT=zephyr" >> $GITHUB_ENV
        echo "export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk" >> $GITHUB_ENV

    - name: Clean build directory
      run: |
        rm -rf build/

    - name: Build firmware
      run: |
        source venv/bin/activate
        pip install west
        west build -b nice_nano_v2 -d build/ -s zmk/app --pristine -- -DSHIELD=lily58_left